# Generated by Django 4.2.28 on 2026-02-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crop",
            name="yield_estimate",
        ),
        migrations.AddField(
            model_name="crop",
            name="crop_type",
            field=models.CharField(default="unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="crop",
            name="expected_yield",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="crop",
            name="next_checkup",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="crop",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="crop",
            name="region",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="crop",
            name="water_usage_liters",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="crop",
            name="yield_efficiency",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="crop",
            name="harvest_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
