# Generated by Django 4.2.27 on 2026-01-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestock',
            name='current_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='livestock',
            name='next_vaccination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='livestock',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='health_status',
            field=models.CharField(max_length=50),
        ),
    ]
