# Generated by Django 4.2.26 on 2025-11-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="supplies",
            old_name="type",
            new_name="category",
        ),
        migrations.AddField(
            model_name="supplies",
            name="cost_per_unit",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="supplies",
            name="last_restocked",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplies",
            name="minimum_required",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="supplies",
            name="notes",
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="supplies",
            name="procurement_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="supplies",
            name="quantity",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="supplies",
            name="unit",
            field=models.CharField(max_length=20),
        ),
    ]
