# Generated by Django 4.2.28 on 2026-02-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="category",
            field=models.CharField(default="N/A", max_length=50),
        ),
        migrations.AddField(
            model_name="equipment",
            name="condition",
            field=models.CharField(default="Good", max_length=50),
        ),
        migrations.AddField(
            model_name="equipment",
            name="hours_used",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="equipment",
            name="last_service_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="maintenance_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="next_checkup",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="purchase_cost",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="equipment",
            name="serial_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="service_interval_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="equipment",
            name="supplier",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="warranty_expiry",
            field=models.DateField(blank=True, null=True),
        ),
    ]
