# Generated by Django 4.2.27 on 2026-02-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="maintenance_due",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
