# Generated by Django 4.2.28 on 2026-02-04 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_livestock_current_value_and_more"),
        ("app", "0002_remove_crop_yield_estimate_crop_crop_type_and_more"),
    ]

    operations = []
