# Generated by Django 4.2.27 on 2026-02-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_equipment_category_equipment_notes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="supplies",
            old_name="type",
            new_name="category",
        ),
        migrations.RemoveField(
            model_name="crop",
            name="yield_estimate",
        ),
        migrations.AddField(
            model_name="crop",
            name="crop_type",
            field=models.CharField(default="unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="crop",
            name="expected_yield",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="crop",
            name="next_checkup",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="crop",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="crop",
            name="region",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="crop",
            name="water_usage_liters",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="crop",
            name="yield_efficiency",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="equipment",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="condition",
            field=models.CharField(default="Good", max_length=50),
        ),
        migrations.AddField(
            model_name="equipment",
            name="hours_used",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="equipment",
            name="last_service_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="maintenance_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="next_checkup",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="purchase_cost",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="equipment",
            name="serial_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="service_interval_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="equipment",
            name="supplier",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="warranty_expiry",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="livestock",
            name="current_value",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="livestock",
            name="next_vaccination_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="livestock",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="livestock",
            name="purchase_price",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="livestock",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplies",
            name="cost_per_unit",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="supplies",
            name="last_restocked",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplies",
            name="minimum_required",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="supplies",
            name="notes",
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="supplies",
            name="procurement_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="crop",
            name="harvest_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="category",
            field=models.CharField(default="N/A", max_length=50),
        ),
        migrations.AlterField(
            model_name="livestock",
            name="health_status",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="supplies",
            name="quantity",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="supplies",
            name="unit",
            field=models.CharField(max_length=20),
        ),
    ]
