# Generated by Django 4.2.28 on 2026-02-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_equipment_active_equipment_category_and_more"),
        ("app", "0003_merge_20260203_2119"),
    ]

    operations = []
