# Generated by Django 4.2.28 on 2026-02-04 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_type_supplies_category_supplies_cost_per_unit_and_more"),
        ("app", "0004_merge_20260204_1052"),
    ]

    operations = []
