# Generated by Django 6.0.4 on 2026-06-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_merge_20260204_1518"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("message", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="INFO",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                ("item_type", models.CharField(blank=True, max_length=50, null=True)),
                ("item_id", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
