# Generated by Django 4.2.29 on 2026-03-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_merge_20260204_1518"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplies",
            name="cost_per_unit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="supplies",
            name="minimum_required",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="supplies",
            name="unit",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
