# Generated by Django 4.2.30 on 2026-05-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_supplies_cost_per_unit_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="livestock",
            old_name="breed",
            new_name="type",
        ),
        migrations.AlterField(
            model_name="livestock",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="livestock",
            name="current_value",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="livestock",
            name="health_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="livestock",
            name="purchase_price",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
