# Generated by Django 6.0.4 on 2026-06-09 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alert"),
        ("app", "0007_rename_breed_livestock_type_alter_livestock_age_and_more"),
    ]

    operations = []
