# Generated by Django 4.2.20 on 2025-07-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_transaction_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
