# Generated by Django 6.0.4 on 2026-06-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_merge_20260609_1749"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livestock",
            name="age",
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="livestock",
            name="current_value",
            field=models.FloatField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="livestock",
            name="health_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="livestock",
            name="notes",
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="livestock",
            name="purchase_price",
            field=models.FloatField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="livestock",
            name="weight",
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="supplies",
            name="cost_per_unit",
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="supplies",
            name="minimum_required",
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="supplies",
            name="quantity",
            field=models.FloatField(max_length=20),
        ),
    ]
