# Generated by Django 5.2.1 on 2025-10-06 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_crop_notes_crop_purchase_date_crop_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='quantity',
        ),
    ]
