# Generated by Django 6.0.4 on 2026-06-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_livestock_age_alter_livestock_current_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livestock",
            name="age",
            field=models.BigIntegerField(blank=True, max_length=20, null=True),
        ),
    ]
