# Generated by Django 6.0.4 on 2026-06-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_livestock_age_alter_livestock_current_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livestock",
            name="age",
            field=models.BigIntegerField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name="livestock",
            name="current_value",
            field=models.FloatField(blank=True, default=0, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name="livestock",
            name="purchase_price",
            field=models.FloatField(blank=True, default=0, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name="livestock",
            name="weight",
            field=models.FloatField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name="supplies",
            name="cost_per_unit",
            field=models.FloatField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name="supplies",
            name="minimum_required",
            field=models.FloatField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name="supplies",
            name="quantity",
            field=models.FloatField(max_length=18),
        ),
        migrations.AlterField(
            model_name="supplies",
            name="unit",
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
