# Generated by Django 6.0.4 on 2026-06-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_livestock_age_alter_livestock_current_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crop",
            name="crop_type",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="crop",
            name="expected_yield",
            field=models.FloatField(default=0, max_length=18),
        ),
        migrations.AlterField(
            model_name="crop",
            name="name",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="crop",
            name="notes",
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="crop",
            name="planting_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="crop",
            name="region",
            field=models.CharField(
                blank=True, default="Unknown", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="crop",
            name="water_usage_liters",
            field=models.FloatField(default=0, max_length=18),
        ),
        migrations.AlterField(
            model_name="crop",
            name="yield_efficiency",
            field=models.FloatField(default=0, max_length=18),
        ),
        migrations.AlterField(
            model_name="livestock",
            name="health_status",
            field=models.CharField(
                blank=True, default="Unknown", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="livestock",
            name="name",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="livestock",
            name="type",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="supplies",
            name="category",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="supplies",
            name="name",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="supplies",
            name="unit",
            field=models.CharField(
                blank=True, default="Unknown", max_length=18, null=True
            ),
        ),
    ]
