# Generated by Django 6.0.4 on 2026-06-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_alter_crop_crop_type_alter_crop_expected_yield_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crop",
            name="expected_yield",
            field=models.FloatField(blank=True, default=0, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name="crop",
            name="water_usage_liters",
            field=models.FloatField(blank=True, default=0, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name="crop",
            name="yield_efficiency",
            field=models.FloatField(blank=True, default=0, max_length=18, null=True),
        ),
    ]
