# Generated by Django 6.0.4 on 2026-06-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_alter_crop_expected_yield_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crop",
            name="crop_type",
            field=models.CharField(default="N/A", max_length=100),
        ),
        migrations.AlterField(
            model_name="crop",
            name="name",
            field=models.CharField(default="N/A", max_length=100),
        ),
        migrations.AlterField(
            model_name="crop",
            name="region",
            field=models.CharField(
                blank=True, default="N/A", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="category",
            field=models.CharField(default="N/A", max_length=100),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="condition",
            field=models.CharField(
                blank=True, default="N/A", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="hours_used",
            field=models.FloatField(blank=True, default=0, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="last_service_by",
            field=models.CharField(
                blank=True, default="N/A", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="location",
            field=models.CharField(
                blank=True, default="N/A", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="maintenance_due",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="maintenance_history",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="name",
            field=models.CharField(default="N/A", max_length=100),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="notes",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="purchase_cost",
            field=models.FloatField(blank=True, default=0, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="serial_number",
            field=models.CharField(
                blank=True, default="N/A", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="service_interval_days",
            field=models.BigIntegerField(
                blank=True, default=0, max_length=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="supplier",
            field=models.CharField(
                blank=True, default="N/A", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="type",
            field=models.CharField(
                blank=True, default="N/A", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="livestock",
            name="health_status",
            field=models.CharField(
                blank=True, default="N/A", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="livestock",
            name="name",
            field=models.CharField(default="N/A", max_length=100),
        ),
        migrations.AlterField(
            model_name="livestock",
            name="type",
            field=models.CharField(default="N/A", max_length=100),
        ),
        migrations.AlterField(
            model_name="supplies",
            name="category",
            field=models.CharField(default="N/A", max_length=100),
        ),
        migrations.AlterField(
            model_name="supplies",
            name="name",
            field=models.CharField(default="N/A", max_length=100),
        ),
        migrations.AlterField(
            model_name="supplies",
            name="unit",
            field=models.CharField(blank=True, default="N/A", max_length=18, null=True),
        ),
    ]
