# Generated by Django 6.0.4 on 2026-06-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_alter_crop_crop_type_alter_crop_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
