# Generated by Django 6.0.4 on 2026-06-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_alter_equipment_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="active",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                max_length=18,
                null=True,
            ),
        ),
    ]
