# Generated by Django 6.0.4 on 2026-06-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_alter_equipment_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="notes",
            field=models.TextField(blank=True, default="", max_length=100, null=True),
        ),
    ]
