# Generated by Django 6.0.4 on 2026-06-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_alter_equipment_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="item_name",
            field=models.CharField(default="N/A", max_length=100),
        ),
        migrations.AddField(
            model_name="transaction",
            name="notes",
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="service_interval_days",
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="livestock",
            name="age",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("Crop", "Crop"),
                    ("Livestock", "Livestock"),
                    ("Equipment", "Equipment"),
                    ("Supplies", "Supplies"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("Sale", "Sale"),
                    ("Purchase", "Purchase"),
                    ("Return", "Return"),
                ],
                max_length=100,
            ),
        ),
    ]
