name: 'Setup Python Environment'
description: 'Sets up Python and installs dependencies'

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.6'

    - name: Install dependencies
      shell: bash
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt