spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blackcreekfarm
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379

analytics:
  redis:
    stream-name: farm-events
    consumer-group: analytics-group
    consumer-name: engine-1
