package com.yublueprint.analytics_engine.service;

import com.lowagie.text.*;
import com.lowagie.text.Font;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Color;
import com.yublueprint.analytics_engine.entity.Livestock;
import com.yublueprint.analytics_engine.repository.LivestockRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.time.LocalDateTime;
import java.util.List;

@Service
@RequiredArgsConstructor
@Slf4j
public class ReportService {

    private final LivestockRepository livestockRepository;

    /**
     * Blueprint-Based PDF Engine: Generates institutional-grade reports.
     * Uses a structural component model for scalability and consistency.
     */
    public ByteArrayInputStream generateLivestockReport() {
        log.info("Reporting Engine: Initiating document blueprint...");
        List<Livestock> dataSet = livestockRepository.findAll();

        Document document = new Document(PageSize.A4);
        ByteArrayOutputStream out = new ByteArrayOutputStream();

        try {
            PdfWriter.getInstance(document, out);
            document.open();

            // Structural Component: Header
            addInstitutionalHeader(document);
            
            // Structural Component: Metadata
            addDocumentMetadata(document, "Livestock Strategy Audit");
            
            // Structural Component: Data Matrix
            addLivestockDataMatrix(document, dataSet);

            document.close();
            log.info("Reporting Engine: Blueprint finalized successfully.");

        } catch (DocumentException ex) {
            log.error("Reporting Engine Failure: Document creation error - {}", ex.getMessage());
        }

        return new ByteArrayInputStream(out.toByteArray());
    }

    private void addInstitutionalHeader(Document document) throws DocumentException {
        Font font = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 22, Color.DARK_GRAY);
        Paragraph header = new Paragraph("BLACK CREEK COMMUNITY FARM", font);
        header.setAlignment(Element.ALIGN_LEFT);
        document.add(header);
        
        Font subFont = FontFactory.getFont(FontFactory.HELVETICA, 10, Color.GRAY);
        document.add(new Paragraph("System Audit & Management Portal (BC-SAMP)", subFont));
        document.add(Chunk.NEWLINE);
    }

    private void addDocumentMetadata(Document document, String titleStr) throws DocumentException {
        Font font = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16);
        Paragraph title = new Paragraph(titleStr, font);
        title.setSpacingAfter(10);
        document.add(title);
        
        Font metaFont = FontFactory.getFont(FontFactory.HELVETICA, 8, Color.GRAY);
        document.add(new Paragraph("Generated by BC-Analytics Engine on " + LocalDateTime.now(), metaFont));
        document.add(new Paragraph("Sensitivity: Operational Internal Use", metaFont));
        document.add(Chunk.NEWLINE);
    }

    private void addLivestockDataMatrix(Document document, List<Livestock> data) throws DocumentException {
        PdfPTable table = new PdfPTable(new float[]{1, 3, 3, 2, 3});
        table.setWidthPercentage(100);
        table.setSpacingBefore(10);

        // Header Style
        Font headFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, Color.WHITE);
        addCellToTable(table, "ID", headFont, Color.BLACK);
        addCellToTable(table, "Asset Name", headFont, Color.BLACK);
        addCellToTable(table, "Breed/Taxonomy", headFont, Color.BLACK);
        addCellToTable(table, "Age (Y)", headFont, Color.BLACK);
        addCellToTable(table, "Health/Status", headFont, Color.BLACK);

        Font bodyFont = FontFactory.getFont(FontFactory.HELVETICA, 9);
        for (Livestock item : data) {
            addCellToTable(table, String.valueOf(item.getId()), bodyFont, null);
            addCellToTable(table, item.getName(), bodyFont, null);
            addCellToTable(table, item.getBreed(), bodyFont, null);
            addCellToTable(table, String.valueOf(item.getAge()), bodyFont, null);
            addCellToTable(table, item.getHealthStatus().toUpperCase(), bodyFont, null);
        }

        document.add(table);
    }

    private void addCellToTable(PdfPTable table, String text, Font font, Color bgColor) {
        PdfPCell cell = new PdfPCell(new Phrase(text, font));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
        cell.setPadding(5);
        if (bgColor != null) cell.setBackgroundColor(bgColor);
        table.addCell(cell);
    }
}
