name: "CI Pipeline"

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  postgres:
    uses: ./.github/workflows/postgres.yml

  test:
    needs: [build, postgres]
    uses: ./.github/workflows/test.yml

  notify:
    needs: [build, test]
    uses: ./.github/workflows/notify.yml