name: Discord Notifications
on:
  workflow_call:

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

    steps:
      - name: ✔️ Notify Discord on PR merge success (Prod only)
        if: ${{ success() && github.event.pull_request.merged == true && github.base_ref == 'Prod' }}
        run: |
          curl -H "Content-Type: application/json" \
               -d "{
                 \"content\": \"✅ *${{ github.event.pull_request.title }}* on branch **${{ env.BRANCH_NAME }}** passed all checks and**_*_*