name: Discord Notifications
on:
  workflow_call:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify on success
        if: ${{ success() && github.event.pull_request.merged == true && github.base_ref == 'Prod' }}
        run: |
          curl -H "Content-Type: application/json" \
               -d "{
                 \"content\": \"✅ *${{ github.event.pull_request.title }}* passed all checks and was launched to **Production** by **${{ github.actor }}** 🚀\"
               }" \
               $DISCORD_WEBHOOK_URL

      - name: Notify on failure
        if: ${{ failure() && github.event_name == 'pull_request' }}
        run: |
          curl -H "Content-Type: application/json" \
               -d "{
                 \"content\": \"💀 *${{ github.event.pull_request.title }}* failed CI.\\n**${{ github.actor }}**, time to debug 🧩\"
               }" \
               $DISCORD_WEBHOOK_URL